spring.application.name=product-catalog-api


spring.datasource.url=jdbc:postgresql://localhost:5432/product-catalog-api
spring.datasource.username=postgres
spring.datasource.password=adminProduct
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
